### ISSUE TITLE
web-search client cycle timings 

### ISSUE THREAD

**Issue by jinweilin7325** [parsa-epfl/cloudsuite#169]
I was trying to change the web-search client cycle timings by adding the following code to search\deploy\run.xml.
`<driverConfig name="SearchDriver">`
`<requestLagTime>`
            `<fixedTime>`
                `<cycleType>cycletime</cycleType>`
                `<cycleTime>2000</cycleTime>`
                `<cycleDeviation>5</cycleDeviation>`
            `</fixedTime>`
`</requestLagTime>`
`</driverConfig>`
but when the client runs ,it reports:
com.sun.faban.driver.ConfigurationException: Badly configured cycle time; you must have one and only one classname
        at com.sun.faban.driver.engine.Mix.configureCycles(Mix.java:282)
        at com.sun.faban.driver.engine.RunInfo$ConfigurationReader.getRunInfo(RunInfo.java:1244)
        at com.sun.faban.driver.engine.RunInfo.read(RunInfo.java:159)
        at com.sun.faban.driver.engine.MasterImpl.runBenchmark(MasterImpl.java:188)
        at com.sun.faban.driver.engine.MasterImpl.main(MasterImpl.java:1566)

Is this the wrong way to change the driver configuration?

**Comment by jinweilin7325** [comment]
Cycle Timings should be modified in search/distributions/Ziphian.java
