### ISSUE TITLE
Data-Analytics error

### ISSUE THREAD

**Issue by saidulshakil** [parsa-epfl/cloudsuite#181]
Can anyone please tell me whether my Benchmark is running or not. I always received the below messages -

MAHOUT_LOCAL is not set; adding HADOOP_CONF_DIR to classpath.
Running on hadoop, using /opt/hadoop-2.7.4/bin/hadoop and HADOOP_CONF_DIR=/opt/hadoop-2.7.4/etc/hadoop
MAHOUT-JOB: /opt/mahout-0.12.2/mahout-examples-0.12.2-job.jar
18/08/15 16:58:35 INFO WikipediaToSequenceFile: Input: /user/root/wiki Out: /user/root/wiki-seq Categories: /root/categories All Files: false
18/08/15 16:58:37 INFO RMProxy: Connecting to ResourceManager at master/172.19.0.2:8032
18/08/15 16:58:38 WARN JobResourceUploader: Hadoop command-line option parsing not performed. Implement the Tool interface and execute your application with ToolRunner to remedy this.
18/08/15 16:58:41 INFO FileInputFormat: Total input paths to process : 1
18/08/15 16:58:44 INFO JobSubmitter: number of splits:5
18/08/15 16:58:44 INFO JobSubmitter: Submitting tokens for job: job_1534352258156_0001
18/08/15 16:58:45 INFO YarnClientImpl: Submitted application application_1534352258156_0001
18/08/15 16:58:45 INFO Job: The url to track the job: http://master:8088/proxy/application_1534352258156_0001/
18/08/15 16:58:45 INFO Job: Running job: job_1534352258156_0001
18/08/15 16:58:59 INFO Job: Job job_1534352258156_0001 running in uber mode : false
18/08/15 16:59:00 INFO Job:  map 0% reduce 0%
18/08/15 16:59:00 INFO Job: Job job_1534352258156_0001 failed with state FAILED due to: Application application_1534352258156_0001 failed 2 times due to AM Container for appattempt_1534352258156_0001_000002 exited with  exitCode: -108
For more detailed output, check application tracking page:http://master:8088/cluster/app/application_1534352258156_0001Then, click on links to logs of each attempt.
Diagnostics: [2018-08-15 16:58:59.245]Opportunistic container queue is full.
[2018-08-15 16:58:59.245]Container is killed before being launched.
Failing this attempt. Failing the application.
18/08/15 16:59:01 INFO Job: Counters: 0
Exception in thread "main" java.lang.IllegalStateException: Job failed!
	at org.apache.mahout.text.WikipediaToSequenceFile.runJob(WikipediaToSequenceFile.java:206)
	at org.apache.mahout.text.WikipediaToSequenceFile.main(WikipediaToSequenceFile.java:130)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.hadoop.util.ProgramDriver$ProgramDescription.invoke(ProgramDriver.java:71)
	at org.apache.hadoop.util.ProgramDriver.run(ProgramDriver.java:144)
	at org.apache.hadoop.util.ProgramDriver.driver(ProgramDriver.java:152)
	at org.apache.mahout.driver.MahoutDriver.main(MahoutDriver.java:195)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.hadoop.util.RunJar.run(RunJar.java:221)
	at org.apache.hadoop.util.RunJar.main(RunJar.java:136)
Mahout: seq2sparse
MAHOUT_LOCAL is not set; adding HADOOP_CONF_DIR to classpath.
Running on hadoop, using /opt/hadoop-2.7.4/bin/hadoop and HADOOP_CONF_DIR=/opt/hadoop-2.7.4/etc/hadoop
MAHOUT-JOB: /opt/mahout-0.12.2/mahout-examples-0.12.2-job.jar
18/08/15 16:59:17 INFO SparseVectorsFromSequenceFiles: Maximum n-gram size is: 2
18/08/15 16:59:19 INFO SparseVectorsFromSequenceFiles: Minimum LLR value: 1.0
18/08/15 16:59:19 INFO SparseVectorsFromSequenceFiles: Number of reduce tasks: 1
18/08/15 16:59:19 INFO SparseVectorsFromSequenceFiles: Tokenizing documents in /user/root/wiki-seq
18/08/15 16:59:19 INFO RMProxy: Connecting to ResourceManager at master/172.19.0.2:8032
18/08/15 16:59:21 INFO JobSubmitter: Cleaning up the staging area /tmp/hadoop-yarn/staging/root/.staging/job_1534352258156_0002
Exception in thread "main" org.apache.hadoop.mapreduce.lib.input.InvalidInputException: Input path does not exist: hdfs://master:8020/user/root/wiki-seq
	at org.apache.hadoop.mapreduce.lib.input.FileInputFormat.singleThreadedListStatus(FileInputFormat.java:323)
	at org.apache.hadoop.mapreduce.lib.input.FileInputFormat.listStatus(FileInputFormat.java:265)
	at org.apache.hadoop.mapreduce.lib.input.SequenceFileInputFormat.listStatus(SequenceFileInputFormat.java:59)
	at org.apache.hadoop.mapreduce.lib.input.FileInputFormat.getSplits(FileInputFormat.java:387)
	at org.apache.hadoop.mapreduce.JobSubmitter.writeNewSplits(JobSubmitter.java:301)
	at org.apache.hadoop.mapreduce.JobSubmitter.writeSplits(JobSubmitter.java:318)
	at org.apache.hadoop.mapreduce.JobSubmitter.submitJobInternal(JobSubmitter.java:196)
	at org.apache.hadoop.mapreduce.Job$10.run(Job.java:1290)
	at org.apache.hadoop.mapreduce.Job$10.run(Job.java:1287)
	at java.security.AccessController.doPrivileged(Native Method)
	at javax.security.auth.Subject.doAs(Subject.java:422)
	at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1746)
	at org.apache.hadoop.mapreduce.Job.submit(Job.java:1287)
	at org.apache.hadoop.mapreduce.Job.waitForCompletion(Job.java:1308)
	at org.apache.mahout.vectorizer.DocumentProcessor.tokenizeDocuments(DocumentProcessor.java:93)
	at org.apache.mahout.vectorizer.SparseVectorsFromSequenceFiles.run(SparseVectorsFromSequenceFiles.java:257)
	at org.apache.hadoop.util.ToolRunner.run(ToolRunner.java:70)
	at org.apache.hadoop.util.ToolRunner.run(ToolRunner.java:84)
	at org.apache.mahout.vectorizer.SparseVectorsFromSequenceFiles.main(SparseVectorsFromSequenceFiles.java:56)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.hadoop.util.ProgramDriver$ProgramDescription.invoke(ProgramDriver.java:71)
	at org.apache.hadoop.util.ProgramDriver.run(ProgramDriver.java:144)
	at org.apache.hadoop.util.ProgramDriver.driver(ProgramDriver.java:152)
	at org.apache.mahout.driver.MahoutDriver.main(MahoutDriver.java:195)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.hadoop.util.RunJar.run(RunJar.java:221)
	at org.apache.hadoop.util.RunJar.main(RunJar.java:136)
Mahout: split
MAHOUT_LOCAL is not set; adding HADOOP_CONF_DIR to classpath.
Running on hadoop, using /opt/hadoop-2.7.4/bin/hadoop and HADOOP_CONF_DIR=/opt/hadoop-2.7.4/etc/hadoop
MAHOUT-JOB: /opt/mahout-0.12.2/mahout-examples-0.12.2-job.jar
18/08/15 16:59:29 WARN MahoutDriver: No split.props found on classpath, will use command-line arguments only
18/08/15 16:59:29 INFO AbstractJob: Command line arguments: {--endPhase=[2147483647], --input=[/user/root/wiki-vectors/tfidf-vectors], --method=[sequential], --overwrite=null, --randomSelectionPct=[20], --sequenceFiles=null, --startPhase=[0], --tempDir=[temp], --testOutput=[/user/root/testing], --trainingOutput=[/user/root/training]}
Exception in thread "main" java.io.FileNotFoundException: File does not exist: /user/root/wiki-vectors/tfidf-vectors
	at org.apache.hadoop.hdfs.DistributedFileSystem$22.doCall(DistributedFileSystem.java:1309)
	at org.apache.hadoop.hdfs.DistributedFileSystem$22.doCall(DistributedFileSystem.java:1301)
	at org.apache.hadoop.fs.FileSystemLinkResolver.resolve(FileSystemLinkResolver.java:81)
	at org.apache.hadoop.hdfs.DistributedFileSystem.getFileStatus(DistributedFileSystem.java:1317)
	at org.apache.mahout.utils.SplitInput.splitDirectory(SplitInput.java:288)
	at org.apache.mahout.utils.SplitInput.splitDirectory(SplitInput.java:279)
	at org.apache.mahout.utils.SplitInput.splitDirectory(SplitInput.java:270)
	at org.apache.mahout.utils.SplitInput.run(SplitInput.java:134)
	at org.apache.hadoop.util.ToolRunner.run(ToolRunner.java:70)
	at org.apache.mahout.utils.SplitInput.main(SplitInput.java:140)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.hadoop.util.ProgramDriver$ProgramDescription.invoke(ProgramDriver.java:71)
	at org.apache.hadoop.util.ProgramDriver.run(ProgramDriver.java:144)
	at org.apache.hadoop.util.ProgramDriver.driver(ProgramDriver.java:152)
	at org.apache.mahout.driver.MahoutDriver.main(MahoutDriver.java:195)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.hadoop.util.RunJar.run(RunJar.java:221)
	at org.apache.hadoop.util.RunJar.main(RunJar.java:136)
Mahout: trainnb
MAHOUT_LOCAL is not set; adding HADOOP_CONF_DIR to classpath.
Running on hadoop, using /opt/hadoop-2.7.4/bin/hadoop and HADOOP_CONF_DIR=/opt/hadoop-2.7.4/etc/hadoop
MAHOUT-JOB: /opt/mahout-0.12.2/mahout-examples-0.12.2-job.jar
18/08/15 16:59:38 WARN MahoutDriver: No trainnb.props found on classpath, will use command-line arguments only
18/08/15 16:59:38 INFO AbstractJob: Command line arguments: {--alphaI=[1.0], --endPhase=[2147483647], --input=[/user/root/training], --labelIndex=[/user/root/labelindex], --output=[/user/root/model], --overwrite=null, --startPhase=[0], --tempDir=[temp], --trainComplementary=null}
18/08/15 16:59:41 INFO deprecation: mapred.input.dir is deprecated. Instead, use mapreduce.input.fileinputformat.inputdir
18/08/15 16:59:41 INFO deprecation: mapred.compress.map.output is deprecated. Instead, use mapreduce.map.output.compress
18/08/15 16:59:41 INFO deprecation: mapred.output.dir is deprecated. Instead, use mapreduce.output.fileoutputformat.outputdir
18/08/15 16:59:41 INFO RMProxy: Connecting to ResourceManager at master/172.19.0.2:8032
18/08/15 16:59:43 INFO FileInputFormat: Total input paths to process : 0
18/08/15 16:59:43 INFO JobSubmitter: number of splits:0
18/08/15 16:59:44 INFO JobSubmitter: Submitting tokens for job: job_1534352258156_0003
18/08/15 16:59:45 INFO YarnClientImpl: Submitted application application_1534352258156_0003
18/08/15 16:59:45 INFO Job: The url to track the job: http://master:8088/proxy/application_1534352258156_0003/
18/08/15 16:59:45 INFO Job: Running job: job_1534352258156_0003
18/08/15 16:59:52 INFO Job: Job job_1534352258156_0003 running in uber mode : false
18/08/15 16:59:52 INFO Job:  map 0% reduce 0%
18/08/15 16:59:52 INFO Job: Job job_1534352258156_0003 failed with state FAILED due to: Application application_1534352258156_0003 failed 2 times due to AM Container for appattempt_1534352258156_0003_000002 exited with  exitCode: -108
For more detailed output, check application tracking page:http://master:8088/cluster/app/application_1534352258156_0003Then, click on links to logs of each attempt.
Diagnostics: [2018-08-15 16:59:51.922]Opportunistic container queue is full.
[2018-08-15 16:59:51.922]Container is killed before being launched.
Failing this attempt. Failing the application.
18/08/15 16:59:52 INFO Job: Counters: 0
18/08/15 16:59:52 INFO MahoutDriver: Program took 14204 ms (Minutes: 0.23673333333333332)
Mahout: testnb
MAHOUT_LOCAL is not set; adding HADOOP_CONF_DIR to classpath.
Running on hadoop, using /opt/hadoop-2.7.4/bin/hadoop and HADOOP_CONF_DIR=/opt/hadoop-2.7.4/etc/hadoop
MAHOUT-JOB: /opt/mahout-0.12.2/mahout-examples-0.12.2-job.jar
18/08/15 17:00:05 WARN MahoutDriver: No testnb.props found on classpath, will use command-line arguments only
18/08/15 17:00:06 INFO AbstractJob: Command line arguments: {--endPhase=[2147483647], --input=[/user/root/testing], --labelIndex=[/user/root/labelindex], --model=[/user/root/model], --output=[/user/root/output], --overwrite=null, --runSequential=null, --startPhase=[0], --tempDir=[temp]}
Exception in thread "main" java.io.FileNotFoundException: File does not exist: /user/root/model/naiveBayesModel.bin
	at org.apache.hadoop.hdfs.server.namenode.INodeFile.valueOf(INodeFile.java:71)
	at org.apache.hadoop.hdfs.server.namenode.INodeFile.valueOf(INodeFile.java:61)
	at org.apache.hadoop.hdfs.server.namenode.FSNamesystem.getBlockLocationsInt(FSNamesystem.java:1836)
	at org.apache.hadoop.hdfs.server.namenode.FSNamesystem.getBlockLocations(FSNamesystem.java:1808)
	at org.apache.hadoop.hdfs.server.namenode.FSNamesystem.getBlockLocations(FSNamesystem.java:1723)
	at org.apache.hadoop.hdfs.server.namenode.NameNodeRpcServer.getBlockLocations(NameNodeRpcServer.java:588)
	at org.apache.hadoop.hdfs.protocolPB.ClientNamenodeProtocolServerSideTranslatorPB.getBlockLocations(ClientNamenodeProtocolServerSideTranslatorPB.java:366)
	at org.apache.hadoop.hdfs.protocol.proto.ClientNamenodeProtocolProtos$ClientNamenodeProtocol$2.callBlockingMethod(ClientNamenodeProtocolProtos.java)
	at org.apache.hadoop.ipc.ProtobufRpcEngine$Server$ProtoBufRpcInvoker.call(ProtobufRpcEngine.java:616)
	at org.apache.hadoop.ipc.RPC$Server.call(RPC.java:982)
	at org.apache.hadoop.ipc.Server$Handler$1.run(Server.java:2217)
	at org.apache.hadoop.ipc.Server$Handler$1.run(Server.java:2213)
	at java.security.AccessController.doPrivileged(Native Method)
	at javax.security.auth.Subject.doAs(Subject.java:422)
	at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1746)
	at org.apache.hadoop.ipc.Server$Handler.run(Server.java:2213)

	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.apache.hadoop.ipc.RemoteException.instantiateException(RemoteException.java:106)
	at org.apache.hadoop.ipc.RemoteException.unwrapRemoteException(RemoteException.java:73)
	at org.apache.hadoop.hdfs.DFSClient.callGetBlockLocations(DFSClient.java:1228)
	at org.apache.hadoop.hdfs.DFSClient.getLocatedBlocks(DFSClient.java:1213)
	at org.apache.hadoop.hdfs.DFSClient.getLocatedBlocks(DFSClient.java:1201)
	at org.apache.hadoop.hdfs.DFSInputStream.fetchLocatedBlocksAndGetLastBlockLength(DFSInputStream.java:306)
	at org.apache.hadoop.hdfs.DFSInputStream.openInfo(DFSInputStream.java:272)
	at org.apache.hadoop.hdfs.DFSInputStream.<init>(DFSInputStream.java:264)
	at org.apache.hadoop.hdfs.DFSClient.open(DFSClient.java:1526)
	at org.apache.hadoop.hdfs.DistributedFileSystem$3.doCall(DistributedFileSystem.java:304)
	at org.apache.hadoop.hdfs.DistributedFileSystem$3.doCall(DistributedFileSystem.java:299)
	at org.apache.hadoop.fs.FileSystemLinkResolver.resolve(FileSystemLinkResolver.java:81)
	at org.apache.hadoop.hdfs.DistributedFileSystem.open(DistributedFileSystem.java:312)
	at org.apache.hadoop.fs.FileSystem.open(FileSystem.java:769)
	at org.apache.mahout.classifier.naivebayes.NaiveBayesModel.materialize(NaiveBayesModel.java:111)
	at org.apache.mahout.classifier.naivebayes.test.TestNaiveBayesDriver.runSequential(TestNaiveBayesDriver.java:113)
	at org.apache.mahout.classifier.naivebayes.test.TestNaiveBayesDriver.run(TestNaiveBayesDriver.java:89)
	at org.apache.hadoop.util.ToolRunner.run(ToolRunner.java:70)
	at org.apache.mahout.classifier.naivebayes.test.TestNaiveBayesDriver.main(TestNaiveBayesDriver.java:66)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.hadoop.util.ProgramDriver$ProgramDescription.invoke(ProgramDriver.java:71)
	at org.apache.hadoop.util.ProgramDriver.run(ProgramDriver.java:144)
	at org.apache.hadoop.util.ProgramDriver.driver(ProgramDriver.java:152)
	at org.apache.mahout.driver.MahoutDriver.main(MahoutDriver.java:195)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.hadoop.util.RunJar.run(RunJar.java:221)
	at org.apache.hadoop.util.RunJar.main(RunJar.java:136)
Caused by: org.apache.hadoop.ipc.RemoteException(java.io.FileNotFoundException): File does not exist: /user/root/model/naiveBayesModel.bin
	at org.apache.hadoop.hdfs.server.namenode.INodeFile.valueOf(INodeFile.java:71)
	at org.apache.hadoop.hdfs.server.namenode.INodeFile.valueOf(INodeFile.java:61)
	at org.apache.hadoop.hdfs.server.namenode.FSNamesystem.getBlockLocationsInt(FSNamesystem.java:1836)
	at org.apache.hadoop.hdfs.server.namenode.FSNamesystem.getBlockLocations(FSNamesystem.java:1808)
	at org.apache.hadoop.hdfs.server.namenode.FSNamesystem.getBlockLocations(FSNamesystem.java:1723)
	at org.apache.hadoop.hdfs.server.namenode.NameNodeRpcServer.getBlockLocations(NameNodeRpcServer.java:588)
	at org.apache.hadoop.hdfs.protocolPB.ClientNamenodeProtocolServerSideTranslatorPB.getBlockLocations(ClientNamenodeProtocolServerSideTranslatorPB.java:366)
	at org.apache.hadoop.hdfs.protocol.proto.ClientNamenodeProtocolProtos$ClientNamenodeProtocol$2.callBlockingMethod(ClientNamenodeProtocolProtos.java)
	at org.apache.hadoop.ipc.ProtobufRpcEngine$Server$ProtoBufRpcInvoker.call(ProtobufRpcEngine.java:616)
	at org.apache.hadoop.ipc.RPC$Server.call(RPC.java:982)
	at org.apache.hadoop.ipc.Server$Handler$1.run(Server.java:2217)
	at org.apache.hadoop.ipc.Server$Handler$1.run(Server.java:2213)
	at java.security.AccessController.doPrivileged(Native Method)
	at javax.security.auth.Subject.doAs(Subject.java:422)
	at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1746)
	at org.apache.hadoop.ipc.Server$Handler.run(Server.java:2213)

	at org.apache.hadoop.ipc.Client.call(Client.java:1476)
	at org.apache.hadoop.ipc.Client.call(Client.java:1413)
	at org.apache.hadoop.ipc.ProtobufRpcEngine$Invoker.invoke(ProtobufRpcEngine.java:229)
	at com.sun.proxy.$Proxy10.getBlockLocations(Unknown Source)
	at org.apache.hadoop.hdfs.protocolPB.ClientNamenodeProtocolTranslatorPB.getBlockLocations(ClientNamenodeProtocolTranslatorPB.java:255)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.hadoop.io.retry.RetryInvocationHandler.invokeMethod(RetryInvocationHandler.java:191)
	at org.apache.hadoop.io.retry.RetryInvocationHandler.invoke(RetryInvocationHandler.java:102)
	at com.sun.proxy.$Proxy11.getBlockLocations(Unknown Source)
	at org.apache.hadoop.hdfs.DFSClient.callGetBlockLocations(DFSClient.java:1226)
	... 30 more

Benchmark time: 109560ms
root@ubuntu:~#

**Comment by saidulshakil** [comment]
@Hnefi @yutannihilation

**Comment by yutannihilation** [comment]
Hi, maybe you mentioned the wrong person?

**Comment by saidulshakil** [comment]
Hi, @yutannihilation , sorry I thought you could help me :(

**Comment by altostratous** [comment]
The benchmark on master branch and docker hub is broken. I can reproduce the issue like this: 
```
#!/bin/bash
docker stop $(docker ps -q) || true
docker rm $(docker ps -aq) || true
docker network create hadoop-net || true 
docker run -d --net hadoop-net --name master --hostname master cloudsuite/data-analytics master
for i in {1..2}; do
	docker stop slave$i || true
	docker rm slave$i || true
	docker run -d --net hadoop-net --name slave$i --hostname slave$i cloudsuite/hadoop slave
done
docker exec master benchmark
```
I think the team is not going to fix this version as some dependencies are no longer supported. 
Please note that #121 is different which is an issue while building the docker images. 
Finally, the team will release the newer version for this benchmark and for now you can build and use the edge version on `dev` branch (remember to checkout the `dev` branch first) like this: 
```
#!/bin/bash

set -e 

docker stop $(docker ps -q) || true
docker rm $(docker ps -aq) || true

docker build -t cloudsuite/java:openjdk8 commons/java/openjdk8
docker build -t cloudsuite/java:latest commons/java/openjdk8
docker build -t cloudsuite/java:openjdk7 commons/java/openjdk7
docker build -t cloudsuite/hadoop:latest commons/hadoop/2.9.1
docker build -t cloudsuite/hadoop:2.9.1 commons/hadoop/2.9.1
docker build -t cloudsuite/data-analytics benchmarks/data-analytics/3.0.0

docker network create hadoop-net || true 

docker run -d --net hadoop-net --name master --hostname master cloudsuite/data-analytics master

for i in {1..2}; do
	docker stop slave$i || true
	docker rm slave$i || true
	docker run -d --net hadoop-net --name slave$i --hostname slave$i cloudsuite/hadoop slave
done

docker exec master benchmark
```

**Comment by saidulshakil** [comment]
@altostratous , I have tried to run your bash script but doesn't work.
Could you please kindly explain the working procedure.
I am working with Ubuntu 16.04 LTS, hypervisor KVM-QEMU.
Thank you for your help.

**Comment by altostratous** [comment]
I'm running this on a system which has, docker installed and properly working; that's all what it requires. 
From your result 

> but doesn't work

and the environment you are running on, I can only say OK it didn't work and the issue may be related to the environment. Please help with providing logs or any other useful information.

**Comment by altostratous** [comment]
>  unable to prepare context: path "commons/java/openjdk8" not found
It means that you don't have the directory for our java image. It may be related to a failure while checking out the `dev` branch or not being updated with it. So before running the script, you can do the following in cloudsuite root directory. Make sure you succeed:
```
git reset --hard # it removes the changes, take care of your work
git clean -f . # it removes the untracked files, take care of your work
git checkout dev
git pull
```

**Comment by saidulshakil** [comment]
Hi,
It's not possible to reset and clean git as I am pulling the images form docker.

**Comment by saidulshakil** [comment]
Hi, @altostratous , I have successfully installed the benchmark.  Thousands thanks to you 👍 .

One question, when I am running the benchmark with one slave, it is taking my all memory of the VM. 
Any solution for this, please?

Thanks again.

**Comment by altostratous** [comment]
Not at all! And again thank you for using cloudsuite.
You can always apply hard or soft limits on containers' memory. It is described [here](https://docs.docker.com/config/containers/resource_constraints/#limit-a-containers-access-to-memory). Also you can find other useful information generally on how to limit resources.

**Comment by saidulshakil** [comment]
Thank you for your quick response. 💯 
If I limit the access to memory, let's say for Hadoop 1GB, will the benchmark will run faster, as it takes too much time. For example, I am sitting since 30 mints and it's just finished 33% of mapping for the first task where there are more tasks to finish.

Thanks again.

**Comment by saidulshakil** [comment]
@altostratous , thanks buddy. 💯
