### ISSUE TITLE
Data-analytics 4.0 Running Error on x86

### ISSUE THREAD

**Issue by Xusine1131** [parsa-epfl/cloudsuite#308]
`java.lang.IllegalArgumentException: java.net.UnknownHostException`

**Comment by neo-apz** [comment]
Can you please write every single command (in order) you ran here as well?

**Comment by neo-apz** [comment]
I followed the instructions in our [doc](https://github.com/parsa-epfl/cloudsuite/blob/dev/docs/benchmarks/data-analytics.md) file and I didn't get your error (although I noticed there are bugs in the doc).
However, I was not able to run the benchmark either due to other errors. It seems no datanode gets registered in Hadoop for some reason.

**Comment by Xusine1131** [comment]
> Can you please write every single command (in order) you ran here as well?

First I pull the image from `cloudsuitetest`:

```
$ docker pull cloudsuitetest/hadoop:2.10.1
$ docker pull cloudsuitetest/data-analytics:4.0
```
Then I start the master:
```
$ docker run -d --net host --name master cloudsuitetest/data-analytics master
```
And I only start one slave:
```
$ docker run -d --net host --name slave01 cloudsuite/hadoop:2.10.1 slave "127.0.0.1"
```
And finaly execute the benchmark:
```
$ docker exec master benchmark
```

**Comment by neo-apz** [comment]
Can you please tell me how your third command works without any errors because there is no `latest` image under that repo and that command should give you an error.

**Comment by Xusine1131** [comment]
Sorry, I just copied from the document but indeed I use `cloudsuitetest/data-analytics:4.0` when starting the master. :sweat_smile:

**Comment by neo-apz** [comment]
Well when one asks you about the exact commands you ran, it should be literally the exact commands you ran, we are trying to debug things here and these small things may in fact be the exact source of the problem.
Your 4th command must also be wrong, unless you actually ran that command which is again wrong.

Could you please tell me literally the exact commands you ran?

**Comment by Xusine1131** [comment]
I'm sorry for my laziness :sweat_smile: . Right now I run the following commands literally in my command line:
```sh
docker pull cloudsuitetest/hadoop:2.10.1
docker pull cloudsuitetest/data-analytics:4.0
docker run -d --net host --name master cloudsuitetest/data-analytics:4.0 master
docker run -d --net host --name slave01 cloudsuitetest/hadoop:2.10.1 slave "127.0.0.1"
docker exec master benchmark
```
And I get the same error.

**Comment by neo-apz** [comment]
OK thanks!

I debugged this a little bit and it seems there is an issue with the URL that is generated to be used for the nodes to connect to each other. If you look at the logs you can see it tries to connect to the localhost/localhost again, which is wrong. This might be a side effect of recent updates and perhaps something config has changed in the newer versions of Hadoop which messes things up for us. My guess is something goes wrong in our entrypoint file for the Hadoop image. You should probably start debugging from there and try just making the basic Hadoop image work with the parameters and make sure the entrypoint is still doing the correct thing.

**Comment by neo-apz** [comment]
Yeah so I just tried to follow an [old instruction](https://github.com/parsa-epfl/cloudsuite/blob/990dc17294cd21ab98a2ad1e9fd474b54aab8055/docs/benchmarks/data-analytics.md) we had before the recent updates which used a dedicated network instead of the host network and that works (adapted to use the recent images). Please try this and confirm that it works for you as  well. To me it seems the problem is with the host network and the way addresses are handled in that script of ours (entrypoint). Because before this we assumed a dedicated network was used but now with the host network things are a bit different and I believe the configuration is not happening properly.

**Comment by Xusine1131** [comment]
> Yeah so I just tried to follow an [old instruction](https://github.com/parsa-epfl/cloudsuite/blob/990dc17294cd21ab98a2ad1e9fd474b54aab8055/docs/benchmarks/data-analytics.md) we had before the recent updates which used a dedicated network instead of the host network and that works (adapted to use the recent images). Please try this and confirm that it works for you as well. To me it seems the problem is with the host network and the way addresses are handled in that script of ours (entrypoint). Because before this we assumed a dedicated network was used but now with the host network things are a bit different and I believe the configuration is not happening properly.
> 
> Another strange thing is that the Hadoop image doesn't `expose` any ports, which is weird as it should expose the ports it's using. This might also cause an issue with the `host` network. Please check this as well.

I used the following command for a dedicated network:
```sh
docker network create hadoop-net
docker run -d --net hadoop-net --name master --hostname master  cloudsuitetest/data-analytics:4.0 master
docker run -d --net hadoop-net --name slave01 --hostname slave01 cloudsuitetest/hadoop:2.10.1 slave
docker exec master benchmark
```
And I saw several similar errors like this:
```
Exception in thread "main" org.apache.hadoop.mapreduce.lib.input.InvalidInputException: Input path does not exist: hdfs://master:8020/user/root/wiki
        at org.apache.hadoop.mapreduce.lib.input.FileInputFormat.singleThreadedListStatus(FileInputFormat.java:329)
        at org.apache.hadoop.mapreduce.lib.input.FileInputFormat.listStatus(FileInputFormat.java:271)
        at org.apache.hadoop.mapreduce.lib.input.FileInputFormat.getSplits(FileInputFormat.java:393)
        at org.apache.hadoop.mapreduce.JobSubmitter.writeNewSplits(JobSubmitter.java:314)
        at org.apache.hadoop.mapreduce.JobSubmitter.writeSplits(JobSubmitter.java:331)
        at org.apache.hadoop.mapreduce.JobSubmitter.submitJobInternal(JobSubmitter.java:202)
        at org.apache.hadoop.mapreduce.Job$11.run(Job.java:1570)
        at org.apache.hadoop.mapreduce.Job$11.run(Job.java:1567)
        at java.base/java.security.AccessController.doPrivileged(Native Method)
        at java.base/javax.security.auth.Subject.doAs(Subject.java:423)
        at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1926)
        at org.apache.hadoop.mapreduce.Job.submit(Job.java:1567)
        at org.apache.hadoop.mapreduce.Job.waitForCompletion(Job.java:1588)
        at org.apache.mahout.text.WikipediaToSequenceFile.runJob(WikipediaToSequenceFile.java:204)
        at org.apache.mahout.text.WikipediaToSequenceFile.main(WikipediaToSequenceFile.java:130)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at org.apache.hadoop.util.ProgramDriver$ProgramDescription.invoke(ProgramDriver.java:71)
        at org.apache.hadoop.util.ProgramDriver.run(ProgramDriver.java:144)
        at org.apache.hadoop.util.ProgramDriver.driver(ProgramDriver.java:152)
        at org.apache.mahout.driver.MahoutDriver.main(MahoutDriver.java:195)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at org.apache.hadoop.util.RunJar.run(RunJar.java:244)
        at org.apache.hadoop.util.RunJar.main(RunJar.java:158)
```

**Comment by neo-apz** [comment]
This error is definitely different than what you had before. Please continue debugging this by diving into the image and trying to run things while you are inside the image so that you can debug it in a better way.
