### ISSUE TITLE
Setup Multiple Cassandra Server Failed on the Same Machine for Data-Serving

### ISSUE THREAD

**Issue by Xusine1131** [parsa-epfl/cloudsuite#329]
## Introduction
When following the document to run multiple server's contains on the same machine, I met an error on running the Cassandra server.
## System Information
`uname` output:
```
Linux moon 5.13.8-zen1-1-zen #1 ZEN SMP PREEMPT Wed, 04 Aug 2021 16:57:43 +0000 x86_64 GNU/Linux
```

## How to Produce
First, set up the seed server by executing:
```
docker run --name cassandra-server-seed --privileged --net host cloudsuitetest/data-serving:server
```
There is no error message.
Then, setup the Cassandra server node by running:
```
docker run --name cassandra-server-1 --privileged --net host -e CASSANDRA_SEEDS=127.0.0.1 cloudsuiteest/data-serving:server
``` 
When running this, the error log is displayed:
```
INFO  [main] 2021-08-05 18:17:40,896 DatabaseDescriptor.java:381 - DiskAccessMode 'auto' determined to be mmap, indexAccessMode is mmap
INFO  [main] 2021-08-05 18:17:40,896 DatabaseDescriptor.java:439 - Global memtable on-heap threshold is enabled at 936MB
INFO  [main] 2021-08-05 18:17:40,896 DatabaseDescriptor.java:443 - Global memtable off-heap threshold is enabled at 936MB
INFO  [main] 2021-08-05 18:17:40,899 FileUtils.java:81 - Cannot initialize un-mmaper.  (Are you using a non-Oracle JVM?)  Compacted data files will not be removed promptly.  Consider using an Oracle JVM or using standard disk access mode
INFO  [main] 2021-08-05 18:17:40,992 RateBasedBackPressure.java:123 - Initialized back-pressure with high ratio: 0.9, factor: 5, flow: FAST, window size: 2000.
INFO  [main] 2021-08-05 18:17:40,992 DatabaseDescriptor.java:773 - Back-pressure is disabled with strategy org.apache.cassandra.net.RateBasedBackPressure{high_ratio=0.9, factor=5, flow=FAST}.
ERROR [main] 2021-08-05 18:17:41,070 CassandraDaemon.java:774 - Port already in use: 7199; nested exception is: 
        java.net.BindException: Address already in use (Bind failed)
java.net.BindException: Address already in use (Bind failed)
        at java.base/java.net.PlainSocketImpl.socketBind(Native Method) ~[na:na]
        at java.base/java.net.AbstractPlainSocketImpl.bind(AbstractPlainSocketImpl.java:436) ~[na:na]
        at java.base/java.net.ServerSocket.bind(ServerSocket.java:395) ~[na:na]
        at java.base/java.net.ServerSocket.<init>(ServerSocket.java:257) ~[na:na]
        at java.base/javax.net.DefaultServerSocketFactory.createServerSocket(ServerSocketFactory.java:231) ~[na:na]
        at org.apache.cassandra.utils.RMIServerSocketFactoryImpl.createServerSocket(RMIServerSocketFactoryImpl.java:42) ~[apache-cassandra-3.11.6.jar:3.11.6]
        at java.rmi/sun.rmi.transport.tcp.TCPEndpoint.newServerSocket(TCPEndpoint.java:670) ~[na:na]
        at java.rmi/sun.rmi.transport.tcp.TCPTransport.listen(TCPTransport.java:324) ~[na:na]
        at java.rmi/sun.rmi.transport.tcp.TCPTransport.exportObject(TCPTransport.java:243) ~[na:na]
        at java.rmi/sun.rmi.transport.tcp.TCPEndpoint.exportObject(TCPEndpoint.java:412) ~[na:na]
        at java.rmi/sun.rmi.transport.LiveRef.exportObject(LiveRef.java:147) ~[na:na]
        at java.rmi/sun.rmi.server.UnicastServerRef.exportObject(UnicastServerRef.java:234) ~[na:na]
        at java.rmi/sun.rmi.registry.RegistryImpl.setup(RegistryImpl.java:220) ~[na:na]
        at java.rmi/sun.rmi.registry.RegistryImpl.<init>(RegistryImpl.java:180) ~[na:na]
        at java.rmi/sun.rmi.registry.RegistryImpl.<init>(RegistryImpl.java:151) ~[na:na]
        at java.rmi/java.rmi.registry.LocateRegistry.createRegistry(LocateRegistry.java:239) ~[na:na]
        at org.apache.cassandra.utils.JMXServerUtils.createJMXServer(JMXServerUtils.java:75) ~[apache-cassandra-3.11.6.jar:3.11.6]
        at org.apache.cassandra.service.CassandraDaemon.maybeInitJmx(CassandraDaemon.java:150) ~[apache-cassandra-3.11.6.jar:3.11.6]
        at org.apache.cassandra.service.CassandraDaemon.setup(CassandraDaemon.java:195) ~[apache-cassandra-3.11.6.jar:3.11.6]
        at org.apache.cassandra.service.CassandraDaemon.activate(CassandraDaemon.java:630) ~[apache-cassandra-3.11.6.jar:3.11.6]
        at org.apache.cassandra.service.CassandraDaemon.main(CassandraDaemon.java:757) ~[apache-cassandra-3.11.6.jar:3.11.6]

```
## Note
1. There is no problem when running the single Cassandra server.
2. hostname is pingable
3. I tried to not expose the 7199 port by modifying the docker file, and it doesn't work

**Comment by Hnefi** [comment]
Won't this obviously fail when using the host network, because both containers will share the same IP and port namespace, and both will try to bind to the host's IP:port combinations? To me this is a non-issue, as I do not expect it to work on the host network. If you want more details, you can find them here:

https://docs.docker.com/network/host/

We should clarify this in our documentation.

**Comment by neo-apz** [comment]
The multi-node setup requires real separate physical nodes, which is fine and makes sense. Hence, I'm closing this. Please just make sure the setup works in the case of multiple physical nodes.

**Comment by Xusine1131** [comment]
I will update the document to highlight this point in case the user wants to repeat it.
